/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/finalRoom.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/finalRoom.glb')
  return (
    <group {...props} dispose={null}>
      <group name="_television" position={[11.832, 7.063, -4.216]} scale={0.077}>
        <mesh name="LCD_Screen" geometry={nodes.LCD_Screen.geometry} material={materials.LCD} position={[-1.293, -50.76, -0.004]} />
        <mesh name="Stand_Chrome" geometry={nodes.Stand_Chrome.geometry} material={materials.Chrome} position={[1.067, -56.614, -0.004]} />
        <mesh name="Stand_Mount" geometry={nodes.Stand_Mount.geometry} material={materials['Glossy Dark Grey']} position={[-1.838, -32.6, -0.004]} />
        <mesh name="TV_Backing" geometry={nodes.TV_Backing.geometry} material={materials['Glossy Dark Grey']} position={[-1.293, -50.76, 0]} />
        <mesh name="TV_Bezel" geometry={nodes.TV_Bezel.geometry} material={materials.Frame} position={[-1.293, -50.721, 0]} />
      </group>
      <group name="lamp" position={[1.275, 7.032, 1.547]} rotation={[0, -0.755, 0]} scale={0.009}>
        <group name="002" position={[1.519, -124.584, -69.017]} rotation={[0, 0.23, 0]} scale={0.696}>
          <mesh name="base" geometry={nodes.base.geometry} material={materials['05 - Default']} position={[64.782, -241.44, 0]} />
          <mesh name="button" geometry={nodes.button.geometry} material={materials['04 - Default']} position={[-7.361, -223.44, 0]} />
          <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['04 - Default']} position={[-121.853, 190.459, 0]} />
          <group name="lamp_shade" position={[-65.166, 130.459, 0]}>
            <mesh name="Mesh026" geometry={nodes.Mesh026.geometry} material={materials['05 - Default']} />
            <mesh name="Mesh026_1" geometry={nodes.Mesh026_1.geometry} material={materials['12 - Defaultss']} />
            <mesh name="Mesh026_2" geometry={nodes.Mesh026_2.geometry} material={materials['10 - Default']} />
            <mesh name="Mesh026_3" geometry={nodes.Mesh026_3.geometry} material={materials['Material #87 Slot #4']} />
            <mesh name="Mesh026_4" geometry={nodes.Mesh026_4.geometry} material={materials['Material #90']} />
          </group>
          <mesh name="pivot_hinge" geometry={nodes.pivot_hinge.geometry} material={materials['04 - Default']} position={[131.049, -223.44, 0]} />
          <mesh name="pole" geometry={nodes.pole.geometry} material={materials['04 - Default']} position={[3.344, -0.702, 0]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <mesh name="lamp_stand" geometry={nodes.lamp_stand.geometry} material={materials.Wood_Stand} position={[11.421, 0.623, 9.054]} scale={0.101} />
      <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.021']} position={[11.421, 6.776, 9.054]} scale={[1.42, 1.006, 1.42]} />
      <mesh name="lamp_inside_1" geometry={nodes.lamp_inside_1.geometry} material={materials.Wood_Top} position={[11.421, 6.777, 9.054]} scale={[0.404, 0.442, 0.404]} />
      <group name="Sphere" position={[11.421, 6.829, 9.054]} scale={0.067}>
        <mesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={materials['Material.022']} />
        <mesh name="Sphere_2" geometry={nodes.Sphere_2.geometry} material={materials.Lamp} />
      </group>
      <mesh name="lamp_inside_2" geometry={nodes.lamp_inside_2.geometry} material={materials['Material.023']} position={[11.421, 6.777, 9.054]} scale={[0.404, 0.442, 0.404]} />
      <mesh name="main_desk" geometry={nodes.main_desk.geometry} material={materials['Material.009']} position={[1.062, 4.465, -2.983]} scale={[0.06, 0.05, 0.06]} />
      <group name="clock" position={[12.596, 9.482, 4.544]} rotation={[0, -1.571, 0]} scale={0.041}>
        <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials.pointer_Mat} />
        <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials.symbol_Mat} />
      </group>
      <mesh name="Sofa_" geometry={nodes.Sofa_.geometry} material={materials['Material.025']} position={[3.629, 2.602, 9.212]} rotation={[0, 1.532, 0]} scale={[0.216, 0.217, 0.217]} />
      <mesh name="panel_wall_texture" geometry={nodes.panel_wall_texture.geometry} material={materials['Material.002']} position={[12.859, 7.849, 4.533]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1, 1.043]} />
      <group name="tv_table" position={[10.635, 2.119, -5.581]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.051, 0.049, 0.057]}>
        <mesh name="Mesh014" geometry={nodes.Mesh014.geometry} material={materials['Material.006']} />
        <mesh name="Mesh014_1" geometry={nodes.Mesh014_1.geometry} material={materials['Material.008']} />
        <mesh name="Mesh014_2" geometry={nodes.Mesh014_2.geometry} material={materials['Material.005']} />
        <mesh name="Mesh014_3" geometry={nodes.Mesh014_3.geometry} material={materials['Material.004']} />
      </group>
      <mesh name="floor_mat" geometry={nodes.floor_mat.geometry} material={materials.Material} position={[0.585, 0.75, -1.042]} scale={7.208} />
      <mesh name="monitor" geometry={nodes.monitor.geometry} material={materials['Material.001']} position={[1.942, 4.416, -2.055]} rotation={[-Math.PI, 0.038, -Math.PI]} scale={8.577} />
      <group name="keyboard" position={[0, 4.442, -1.895]} rotation={[Math.PI / 2, 0, 1.681]} scale={[0.133, 0.133, 0.096]}>
        <mesh name="Mesh020" geometry={nodes.Mesh020.geometry} material={materials.blinn1} />
        <mesh name="Mesh020_1" geometry={nodes.Mesh020_1.geometry} material={materials.blinn2} />
      </group>
      <mesh name="mouse" geometry={nodes.mouse.geometry} material={materials['Material.029']} position={[0, 4.323, 1.086]} rotation={[Math.PI / 2, 0, 2.599]} scale={0.201} />
      <mesh name="black_shelf_" geometry={nodes.black_shelf_.geometry} material={materials['Material.014']} position={[3.107, 8.611, 11.155]} scale={0.024} />
      <mesh name="office_chair" geometry={nodes.office_chair.geometry} material={materials['191,191,191']} position={[-3.045, 0.684, -1.044]} rotation={[-2.986, 1.216, 3.02]} scale={0.057} />
      <group name="greyshelf" position={[11.973, 10.963, -2.195]} rotation={[0, 1.542, 0]} scale={[1, 0.056, 1]}>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.greycolor} />
        <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials['Blanco.001']} />
      </group>
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.greycolor} position={[11.978, 12.239, -4.968]} rotation={[0, -0.025, 0]} scale={[1, 1, 1.163]} />
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.greycolor} position={[11.978, 13.516, -2.207]} rotation={[0, -0.025, 0]} scale={[1, 1, 1.225]} />
      <mesh name="polySurface8" geometry={nodes.polySurface8.geometry} material={materials.eb_house_plant_01} position={[-5.11, 0.551, 8.939]} rotation={[Math.PI / 2, 0, -0.216]} scale={0.158} />
      <mesh name="polySurface7" geometry={nodes.polySurface7.geometry} material={materials['eb_house_plant_01.002']} position={[10.127, 1.011, 3.188]} rotation={[Math.PI / 2, 0, 0]} scale={0.132} />
      <mesh name="hitbox1" geometry={nodes.hitbox1.geometry} material={materials['Material.007']} position={[-0.164, 4.18, -3.038]} rotation={[Math.PI, 0, 0]} />
      <mesh name="hitbox2" geometry={nodes.hitbox2.geometry} material={materials['Material.010']} position={[11.926, 7.236, -2.802]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1.261, 1]} />
      <mesh name="hitbox3" geometry={nodes.hitbox3.geometry} material={materials['Material.011']} position={[1.798, 2.833, 8.902]} />
      <mesh name="hitbox_marker_1" geometry={nodes.hitbox_marker_1.geometry} material={materials['Material.114']} position={[4.226, 8.115, 2.874]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="hitbox_marker_2" geometry={nodes.hitbox_marker_2.geometry} material={materials['Material.115']} position={[12.569, 9.628, 1.076]} rotation={[Math.PI, 0, Math.PI]} scale={[0.291, 1.017, 0.971]} />
      <mesh name="hitbox_marker_3" geometry={nodes.hitbox_marker_3.geometry} material={materials['Material.116']} position={[6.706, 8.115, 10.856]} rotation={[Math.PI, 0, Math.PI]} scale={[1.233, 1, 0.408]} />
      <group name="walls" position={[2.629, 0.631, 1.002]} scale={10.399}>
        <mesh name="walls_1" geometry={nodes.walls_1.geometry} material={materials['wall color']} />
        <mesh name="walls_2" geometry={nodes.walls_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh name="base-plane" geometry={nodes['base-plane'].geometry} material={materials['Material.017']} position={[28.266, 0, 23.564]} scale={105.587} />
    </group>
  )
}

useGLTF.preload('/finalRoom.glb')
